### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by Ga-Wa** [jmmedel/Laravel__Frame__Work_Blog#2]
![default](https://user-images.githubusercontent.com/41312570/51653378-836e0a00-1fd6-11e9-9045-931c24fc37ac.JPG)

エラー発生します

**Comment by jmmedel** [comment]
ありがとうございました後でなおします

**Comment by jmmedel** [comment]
１．Ｃｌｏｎｅ　https://github.com/jmmedel/Laravel__Frame__Work_Blog.git
1. https://nodejs.org/en/
2. https://getcomposer.org/download/
3. https://www.apachefriends.org/download.ht
全部初めて　インストールかな
https://github.com/jmmedel/Laravel__Frame__Work_Blog
